{"name": "test_add[erro]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 110 == 100", "trace": "self = <tset_case.test_cacl_case.Testcaclcase object at 0x044A2190>, get_cacl = <tset_case.cacl.cacl object at 0x04528268>, a = 100, b = 10, expect = 100\n\n    @pytest.mark.parametrize(\"a,b,expect\", getyaml()[0], ids=getyaml()[1])\n    def test_add(self, get_cacl, a, b, expect):\n        result = get_cacl.add(a, b)\n>       assert result == expect\nE       assert 110 == 100\n\ntest_cacl_case.py:42: AssertionError"}, "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "10"}, {"name": "expect", "value": "100"}], "start": 1623311628387, "stop": 1623311628387, "uuid": "e795e10d-55f0-425a-8e7d-5419959c7085", "historyId": "ec264a9b58ca11fd1152a162fcad9da4", "testCaseId": "7f5a6d85be1e76f40f2c67e1a61b832f", "fullName": "test_cacl_case.Testcaclcase#test_add", "labels": [{"name": "suite", "value": "test_cacl_case"}, {"name": "subSuite", "value": "Testcaclcase"}, {"name": "host", "value": "BB-202009-DN003"}, {"name": "thread", "value": "89176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cacl_case"}]}